### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram,

I'm a bot and I work on behalf of [Adrian][adius].
If my merge request helped to improve this repository,
please consider to [star my repo][repo] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my dad will try to fix me.

Love, hugs and kisses,
your [Feram][feram]

[adius]: https://github.com/adius
[feram]: https://github.com/ferambot
[repo]: https://github.com/ferambot/feram
[issues]: https://github.com/ferambot/feram/issues

### CODE REVIEW

**Comment by adius** [comment]
Hi, just wanted to know why you closed the pull request?
I added some missing fields and used the default formatting for package files.
Whenever you use `npm install <something>` or any npm tool to modify the package file
it automatically formats it like this…

**Comment by eventEmitter** [comment]
Hi

It's nice if you are adding missing properties, but:
- you didn't keep my formatting, i like it as it is
- because you removed the formatting in the pull request the diff shows not the actual differences

since you didn't care about the formatting of the file and there is no real issue to fix and the pull request was made by a bot i classify this pull request as spam. please don't create any pull request of this quality on any of the repositories i have control over.

thanks

**Comment by adius** [comment]
Thanks for your feedback!

> you didn't keep my formatting, i like it as it is

I can completely relate to that.
I used to format my package files with tabs,
but npm basically enforces the 2 spaces formatting style: https://github.com/npm/npm/pull/3062

At first I was really angry for not giving the user the option to change it,
but nowadays I think it's actually a good thing!
If we all agree to format package files the same way I think we're better off.
At the end of the day it's just bikeshedding…

>  the pull request was made by a bot

Nope. My bot just authored the commit.
I was the one who created them and submitted the pull request.

**Comment by adius** [comment]
…but yeah, the pull request message should make clear who is actually responsible for the pull request.
I have already created an issue for that.

**Comment by eventEmitter** [comment]
... i'm not interested in testing some random dudes software -> spam.

**Comment by adius** [comment]
You're testing nothing.
That was an absolute valid pull request from me and I still think you should merge it.
But if you don't want to that's of course perfectly fine…

**Pull request closed without merging**
